name: Labeler
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  check-should-run:
    uses: ./.github/workflows/allow_workflow_run.yml

  main:
    runs-on: ubuntu-24.04
    needs: check-should-run
    if: needs.check-should-run.outputs.should_run == 'true'
    steps:
      - name: Run Labeler
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          sync-labels: true
